# Tensor Flow Fundamentals

In [11]:
import tensorflow as tf
import numpy as np
tf.debugging.set_log_device_placement(False)

In [2]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
tf.debugging.set_log_device_placement(True)

Num GPUs Available:  1


## TF Constant (scalar,vector,matrix,tensor)

In [3]:
scalar = tf.constant(7)   
print(scalar)

vector = tf.constant([19,19])
print(vector)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(7, shape=(), dtype=int32)
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor([19 19], shape=(2,), dtype=int32)


In [4]:
matrix = tf.constant([[10,10],
                      [9,10]])
print(matrix)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(
[[10 10]
 [ 9 10]], shape=(2, 2), dtype=int32)


In [5]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
print(tensor.ndim)


Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
3


In [6]:
print(tf.constant(9))

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(9, shape=(), dtype=int32)


## Tf Variable

In [7]:
#Tf Constants are inmutable objects

#Tf Variables are mutable objects
tf.debugging.set_log_device_placement(False)
changeable_tensor = tf.Variable([10,10])
changeable_tensor

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10])>

In [8]:
#Random Tensor from a uniform distribution 
random_tensor = tf.random.uniform([2,10])
random_tensor                       

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op RandomUniform in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0.7595624 , 0.3228842 , 0.26865697, 0.89515007, 0.1607306 ,
        0.08748698, 0.25201237, 0.98799825, 0.7879336 , 0.19275641],
       [0.41668236, 0.22575867, 0.55637205, 0.44001245, 0.7175741 ,
        0.67268276, 0.29939222, 0.09737003, 0.8132031 , 0.32403088]],
      dtype=float32)>

In [10]:
#Shuffle tensors, in the process of training nn the tensor values initialices random and shuffled

not_shuffled = tf.constant([[10,10],
                            [9,10]])
shuffled = tf.random.shuffle(not_shuffled)
shuffled    

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op RandomShuffle in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 10],
       [10, 10]])>

### Np.Arrays to Tensors
Tensor can be run on GPU, np.arrays don't

In [17]:
numpy_A = np.arange(10,dtype=np.int32)
numpy_A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
tensor_A = tf.constant(numpy_A)
tensor_A

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [23]:
tensor_B = tf.constant(numpy_A,shape=(2,5))
tensor_B

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Reshape in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])>

## Getting information from tensors
* Shape
* Rank
* Axis & dimention
* Sizee

In [28]:
rank4_tensor = tf.zeros(shape=(2,3,3,2))
rank4_tensor

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 3, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
rank4_tensor.shape, rank4_tensor.ndim,tf.size(rank4_tensor)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0


(TensorShape([2, 3, 3, 2]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=36>)

In [33]:
print(f"Shape 4d tensor: {rank4_tensor.shape}")
print(f"Dim 4d tensor : {rank4_tensor.ndim}")
print(f"Size 4d tensor: {tf.size(rank4_tensor)}")

Shape 4d tensor: (2, 3, 3, 2)
Dim 4d tensor : 4
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Size 4d tensor: 36


## Indexing Tensors
Same as lists, more dimensiones are added 

In [37]:
rank2_tensor = tf.constant([[23,26],
                            [10,30]])

#Add extra dimension to tensor
rank3_tensor = rank2_tensor[...,tf.newaxis]
rank3_tensor

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[23],
        [26]],

       [[10],
        [30]]])>

In [39]:
#Expand dimensions
    #Expand the dim in the specified position

tf.expand_dims(rank2_tensor,axis=0)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ExpandDims in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[23, 26],
        [10, 30]]])>

# Tensor Operations
* Mul
* Div
* Sum
* Substract

Built in tf methods are much faster because of gpu..

In [43]:
matrix_A = tf.constant([[10,3,8],
                        [4,4,4],
                        [19,5,3]])

matrix_B =  tf.constant([[10,3,8],
                         [4,4,4],
                         [19,5,3]])

tf.matmul(matrix_A,matrix_B)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[264,  82, 116],
       [132,  48,  60],
       [267,  92, 181]])>

In [44]:
matrix_A @ matrix_B

Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[264,  82, 116],
       [132,  48,  60],
       [267,  92, 181]])>