# Tensor Flow Fundamentals

In [1]:
import tensorflow as tf
import numpy as np
tf.debugging.set_log_device_placement(False)

In [8]:
X = np.array([200,17])
Y = np.array([[200,22]])
Z = np.array([[[1,2,3]]])
print(f"X_shape: {X.shape,X.ndim} Y_shape: {Y.shape,Y.ndim} Z_shape:{Z.shape,Z.ndim}")

X_shape: ((2,), 1) Y_shape: ((1, 2), 2) Z_shape:((1, 1, 3), 3)


In [2]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
tf.debugging.set_log_device_placement(True)

Num GPUs Available:  1


## TF Constant (scalar,vector,matrix,tensor)

In [3]:
scalar = tf.constant(7)   
print(scalar)

vector = tf.constant([19,19])
print(vector)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(7, shape=(), dtype=int32)
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor([19 19], shape=(2,), dtype=int32)


In [4]:
matrix = tf.constant([[10,10],
                      [9,10]])
print(matrix)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(
[[10 10]
 [ 9 10]], shape=(2, 2), dtype=int32)


In [5]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
print(tensor.ndim)


Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
3


In [6]:
print(tf.constant(9))

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(9, shape=(), dtype=int32)


## Tf Variable

In [7]:
#Tf Constants are inmutable objects

#Tf Variables are mutable objects
tf.debugging.set_log_device_placement(False)
changeable_tensor = tf.Variable([10,10])
changeable_tensor

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10])>

In [8]:
#Random Tensor from a uniform distribution 
random_tensor = tf.random.uniform([2,10])
random_tensor                       

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op RandomUniform in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0.33305633, 0.5129324 , 0.31656456, 0.48927104, 0.11989379,
        0.24042404, 0.38262653, 0.16670477, 0.36337495, 0.1851846 ],
       [0.03850555, 0.37915826, 0.16598976, 0.01828623, 0.04720783,
        0.20498025, 0.80907   , 0.10909748, 0.10924757, 0.86719906]],
      dtype=float32)>

In [9]:
#Shuffle tensors, in the process of training nn the tensor values initialices random and shuffled

not_shuffled = tf.constant([[10,10],
                            [9,10]])
shuffled = tf.random.shuffle(not_shuffled)
shuffled    

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op RandomShuffle in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 10],
       [10, 10]])>

### Np.Arrays to Tensors
Tensor can be run on GPU, np.arrays don't

In [12]:
numpy_A = np.arange(10,dtype=np.int32)
numpy_A.shape,numpy_A.dtype

((10,), dtype('int32'))

In [10]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [12]:
tensor_B = tf.constant(numpy_A,shape=(2,5))
tensor_B

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Reshape in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])>

### Getting information from tensors
* Shape
* Rank
* Axis & dimention
* Sizee

In [13]:
rank4_tensor = tf.zeros(shape=(2,3,3,2))
rank4_tensor

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Fill in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 3, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [14]:
rank4_tensor.shape, rank4_tensor.ndim,tf.size(rank4_tensor)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0


(TensorShape([2, 3, 3, 2]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=36>)

In [15]:
print(f"Shape 4d tensor: {rank4_tensor.shape}")
print(f"Dim 4d tensor : {rank4_tensor.ndim}")
print(f"Size 4d tensor: {tf.size(rank4_tensor)}")

Shape 4d tensor: (2, 3, 3, 2)
Dim 4d tensor : 4
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Size 4d tensor: 36


### Indexing Tensors
Same as lists, more dimensiones are added 

In [16]:
rank2_tensor = tf.constant([[23,26],
                            [10,30]])

#Add extra dimension to tensor
rank3_tensor = rank2_tensor[...,tf.newaxis]
rank3_tensor

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[23],
        [26]],

       [[10],
        [30]]])>

In [17]:
#Expand dimensions
    #Expand the dim in the specified position

tf.expand_dims(rank2_tensor,axis=0)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ExpandDims in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[23, 26],
        [10, 30]]])>

### Tensor Operations
* Mul
* Div
* Sum
* Substract

Built in tf methods are much faster because of gpu..

In [18]:
matrix_A = tf.constant([[10,3,8],
                        [4,4,4],
                        [19,5,3]])

matrix_B =  tf.constant([[10,3,8],
                         [4,4,4],
                         [19,5,3]])

tf.matmul(matrix_A,matrix_B)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[264,  82, 116],
       [132,  48,  60],
       [267,  92, 181]])>

In [19]:
matrix_A @ matrix_B

Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[264,  82, 116],
       [132,  48,  60],
       [267,  92, 181]])>

In [20]:
matrix_C = tf.constant([[1,2],
                        [2,2],
                        [3,9]])

matrix_D = tf.constant([[1,3]])

matrix_C @ tf.transpose(matrix_D)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Transpose in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op MatMul in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 7],
       [ 8],
       [30]])>

## Change Dtype of Tensors
Default dtype if int32 for 32 bits preccision, but for acceleration issues
using 16bit dtypes accelerate calculation

In [21]:
bit32 = tf.constant([1,2,3,4,5])
bit32

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [22]:
bit16 = tf.cast(bit32,dtype=tf.int16)
bit16

Executing op Cast in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(5,), dtype=int16, numpy=array([1, 2, 3, 4, 5], dtype=int16)>

### Tensor Agregation

In [27]:
# Abs Value
D = tf.constant([-7,-8,-4,-5])
tf.abs(D)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Abs in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([7, 8, 4, 5])>

In [30]:
ran3t = tf.random.uniform((2,2,2),0,3)
ran3t

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op RandomUniform in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1.381838 , 0.3273332],
        [2.6352103, 1.9380584]],

       [[0.1672275, 1.3015509],
        [1.8146585, 1.7531934]]], dtype=float32)>

In [31]:
tf.reduce_mean(ran3t)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mean in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(), dtype=float32, numpy=1.4148839>

In [33]:
tf.reduce_min(ran3t)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Min in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(), dtype=float32, numpy=0.1672275>

In [35]:
np.mean(ran3t)

1.4148839

In [36]:
tf.reduce_max(ran3t)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Max in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(), dtype=float32, numpy=2.6352103>

In [37]:
tf.reduce_sum(ran3t)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Sum in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(), dtype=float32, numpy=11.319071>

In [41]:
tf.math.reduce_std(ran3t)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mean in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Sub in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Square in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mean in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Sqrt in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(), dtype=float32, numpy=0.7738322>

In [42]:
tf.math.reduce_variance(ran3t)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mean in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Sub in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Square in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Mean in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(), dtype=float32, numpy=0.5988163>

### Tensor Positional Argument 
positional max/min

In [47]:
r3 = tf.Variable([1,5,6,7,20],dtype="float64")
r3

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Variable 'Variable:0' shape=(5,) dtype=float64, numpy=array([ 1.,  5.,  6.,  7., 20.])>

In [48]:
tf.argmax(r3)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ArgMax in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [49]:
r3[tf.argmax(r3)]

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ArgMax in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Pack in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Pack in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Pack in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(), dtype=float64, numpy=20.0>

In [50]:
r3[tf.argmin(r3)]

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ArgMin in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Pack in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Pack in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Pack in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(), dtype=float64, numpy=1.0>

### Squeeze Tensors to 1D

In [54]:
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G;

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op RandomUniform in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Reshape in device /job:localhost/replica:0/task:0/device:GPU:0


In [52]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [53]:
squeezedG = tf.squeeze(G)
squeezedG.shape

Executing op Squeeze in device /job:localhost/replica:0/task:0/device:GPU:0


TensorShape([50])

## One-Hot Encoding Tensors

In [59]:
index = [0,1,2,3]

tf.one_hot(index,depth=4)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op OneHot in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [61]:
W = tf.range(1,10,2)
W

Executing op Range in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [62]:
tf.square(W)

Executing op Square in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 1,  9, 25, 49, 81])>

In [66]:
tf.sqrt(tf.cast(W,dtype=tf.float32))

Executing op Cast in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Sqrt in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.       , 1.7320509, 2.2360682, 2.6457515, 3.0000002],
      dtype=float32)>

In [70]:
tf.math.log(tf.cast(W,dtype=tf.float32))

Executing op Cast in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Log in device /job:localhost/replica:0/task:0/device:GPU:0


<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([0.       , 1.0986123, 1.609438 , 1.9459102, 2.1972246],
      dtype=float32)>

In [74]:
!nvidia-smi

Mon Jul 17 21:41:47 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 532.03                 Driver Version: 532.03       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce 940M           WDDM | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8               N/A /  N/A|   1477MiB /  2048MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--